---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-postiz
spec:
  description: Postgresql cluster for Postiz
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql registryUrl=ghcr.io
  imageName: ghcr.io/cloudnative-pg/postgresql:17.1
  instances: 1
  storage:
    size: 5Gi
    storageClass: longhorn-basic
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
  bootstrap:
    initdb:
      database: postizdb
      owner: postizusr
      secret:
        name: postiz-db-secret
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  # Bootstrap to recover from an existing backup
  # Note: previousCluster needs to be set to the name of the previous cluster when recovering from an existing cnpg cluster.
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postiz-postgres17-v1
  backup:
    retentionPolicy: 7d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://k8s-postgres/postiz/
      endpointURL: https://s3.${SECRET_DOMAIN}
      serverName: &currentCluster postiz-postgres17-v1
      s3Credentials:
        accessKeyId:
          name: postiz-db-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: postiz-db-secret
          key: SECRET_ACCESS_KEY
 # Note: externalClusters is needed when recovering from an existing cnpg cluster
 #  externalClusters:
 #    - name: *previousCluster
 #      barmanObjectStore:
 #        <<: *barmanObjectStore
 #        serverName: *previousCluster
