---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wazuh
  namespace: security
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"
    controllers:
      manager:
        replicas: 1
        strategy: RollingUpdate
        containers:
          manager:
            image:
              repository: wazuh/wazuh-manager
              tag: 4.11.2@sha256:d4becaac12c791703a8dd99463aa1b484222d01f4f9dc58dfdac1040c0f69845
            env:
              - name: INDEXER_URL
                value: http://wazuh-indexer:9200
              - name: INDEXER_USERNAME
                value: admin
              - name: INDEXER_PASSWORD
                value: admin
              - name: FILEBEAT_SSL_VERIFICATION_MODE
                value: none
              - name: API_USERNAME
                value: wazuh-wui
              - name: API_PASSWORD
                value: MyS3cr37P450r.*-
      indexer:
        replicas: 1
        containers:
          indexer:
            image:
              repository: wazuh/wazuh-indexer
              tag: 4.11.2@sha256:f2ab22b5330eec80e8cdfc6402384d58d507619b692d834eda9b7ddc9abdc99a
            env:
              - name: OPENSEARCH_JAVA_OPTS
                value: "-Xms1g -Xmx1g"
              - name: NODE_NAME
                value: wazuh.indexer
              - name: CLUSTER_NAME
                value: wazuh-cluster
              - name: PLUGINS_SECURITY_SSL_HTTP_ENABLED
                value: "false"
      dashboard:
        replicas: 1
        containers:
          dashboard:
            image:
              repository: wazuh/wazuh-dashboard
              tag: 4.11.2@sha256:56c85dea15ad3b319c93f830b5f7097d8071bc22441628d00552cf8a507e056f
            env:
              - name: WAZUH_API_URL
                value: http://wazuh.manager
              - name: DASHBOARD_USERNAME
                value: kibanaserver
              - name: DASHBOARD_PASSWORD
                value: kibanaserver
              - name: API_USERNAME
                value: wazuh-wui
              - name: API_PASSWORD
                value: MyS3cr37P450r.*-
              - name: SERVER_SSL_ENABLED
                value: "false"
    service:
      manager:
        controller: manager
        ports:
          agent:
            port: 1514
          cluster:
            port: 1515
          syslog:
            port: 514
            protocol: UDP
          api:
            port: 55000
      indexer:
        controller: indexer
        ports:
          http:
            port: 9200
      dashboard:
        controller: dashboard
        ports:
          https:
            port: 5601
