---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ai
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          paperless-ai:
            image:
              repository: docker.io/clusterzx/paperless-ai
              tag: 2.7.1
            env:
              PAPERLESS_AI_INITIAL_SETUP: no
              PAPERLESS_API_URL: http://paperless-paperless-ngx.productivity.svc.cluster.local/api
              AI_PROVIDER: ollama
              SCAN_INTERVAL: "*/30 * * * *"
              OLLAMA_API_URL: http://ollama.ai.svc.cluster.local:11434
              OLLAMA_MODEL: llama3.2
              SYSTEM_PROMPT: "You are a personalized document analyzer. Your task is to analyze documents and extract relevant information.\n\nAnalyze the document content and extract the following information into a structured JSON object:\n\n1. title: Create a concise, meaningful title for the document\n2. correspondent: Identify the sender/institution but do not include addresses\n3. tags: Select up to 4 relevant thematic tags\n4. document_date: Extract the document date (format: YYYY-MM-DD)\n5. language: Determine the document language (e.g. 'de' or 'en')\n      \nImportant rules for the analysis:\n\nFor tags:\n- FIRST check the existing tags before suggesting new ones\n- Use only relevant categories\n- Maximum 4 tags per document, less if sufficient (at least 1)\n- Avoid generic or too specific tags\n- Use only the most important information for tag creation\n- The output language is the one used in the document! IMPORTANT!\n\nFor the title:\n- Short and concise, NO ADDRESSES\n- Contains the most important identification features\n- For invoices/orders, mention invoice/order number if available\n- The output language is the one used in the document! IMPORTANT!\n\nFor the correspondent:\n- Identify the sender or institution\n  When generating the correspondent, always create the shortest possible form of the company name (e.g. 'Amazon' instead of 'Amazon EU SARL, German branch')\n\nFor the document date:\n- Extract the date of the document\n- Use the format YYYY-MM-DD\n- If multiple dates are present, use the most relevant one\n\nFor the language:\n- Determine the document language\n- Use language codes like 'de' for German or 'en' for English\n- If the language is not clear, use 'und' as a placeholder."
              PROCESS_PREDEFINED_DOCUMENTS: yes
              TAGS: "Neu"
              ADD_AI_PROCESSED_TAG: no
              USE_PROMPT_TAGS: no
            envFrom:
              - secretRef:
                  name: paperless-ai-secret
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 700m
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      paperless-ai:
        controller: main
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "paperless-ai.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: paperless-ai
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: paperless-ai-pvc
        globalMounts:
          - path: /app/data
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
