apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 1m
  chart:
    spec:
      chart: velero
      version: 8.7.1
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      useSecret: false
    configuration:
      volumeSnapshotLocation:
        - name: default
          provider: csi
          config:
            snapshotClass: nfs
      extraEnvVars:
        TZ: "${TIMEZONE}"
    schedules:
      daily-csi-snapshots:
        schedule: "00 01 * * *"
        template:
          ttl: "168h" # 7 days
          includedNamespaces:
            - productivity
            - storage-system
          snapshotVolumes: true
    snapshotsEnabled: true
    backupsEnabled: true
    deployNodeAgent: true
    upgradeCRDs: true
    cleanUpCRDs: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
