apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 1m
  chart:
    spec:
      chart: velero
      version: 8.7.1
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      existingSecret: velero-secret
    configuration:
      backupStorageLocation:
        - name: default
          bucket: k8s-velero
          provider: aws
          default: true
          config:
            region: eu-central-1
            s3Url: https://s3.{$SECRET_DOMAIN}
      volumeSnapshotLocation:
        - name: default
          provider: csi
          config:
            snapshotClass: nfs
      extraEnvVars:
        TZ: "${TIMEZONE}"
    schedules:
      daily-snapshot:
        # At 1:00am every day
        schedule: "00 01 * * *"
        template:
          ttl: "72h" # 3 days retention
          includedNamespaces:
            - productivity
          snapshotVolumes: true
      weekly-backup:
        # At the end of the week on a Sunday at 3:00am
        schedule: "00 03 * * 0"
        template:
          ttl: "72h" # 3 days retention
    snapshotsEnabled: true
    backupsEnabled: true
    deployNodeAgent: true
    upgradeCRDs: true
    cleanUpCRDs: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
