---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
spec:
  interval: 30m
  chart:
    spec:
      chart: ollama
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    ollama:
      gpu:
        enabled: false
      models:
        pull:
          - llama3.2
          - mistral
          - deepseek-r1
        run:
          - llama3.2
    extraEnv:
      - name: OLLAMA_DEBUG
        value: "1"
    ingress:
      enabled: true
      className: internal
      hosts:
        - host: ai.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    persistentVolume:
      enabled: true
      accessMode: ReadWriteOnce
      size: 50Gi
      storageClass: openebs-hostpath
    resources:
      requests:
        cpu: 200m
        memory: 2Gi
      limits:
        memory: 12Gi
