---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          ollama:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.5.12.@sha256:822eb51abb760afceecaedfceb09e70963af73d336170da0174e1c1c721cf01c
            env:
              - name: TZ
                value: ${TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
              fsGroup: 3000
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 10Gi
    service:
      ollama:
        controller: main
        ports:
          http:
            port: 11434
    persistence:
      models:
        enabled: true
        existingClaim: ollama-models
        advancedMounts:
          main:
            ollama:
              - path: *path
