---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
spec:
  interval: 30m
  chart:
    spec:
      chart: ollama
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    updateStrategy:
      type: RollingUpdate
    image:
      repository: ollama/ollama
      tag: 0.5.12
      pullPolicy: IfNotPresent
    ollama:
      gpu:
        enabled: false
      models:
        pull:
          - llama3.2
          - mistral
          - deepseek-r1
        run:
          - deepseek-r1
    extraEnv:
      - name: OLLAMA_DEBUG
        value: "1"
    service:
      type: ClusterIP
      port: 11434
      tls:
        - hosts:
           - *host
    persistentVolume:
      enabled: true
      accessMode: ReadWriteOnce
      size: 50Gi
      storageClass: openebs-hostpath
    resources:
      requests:
        cpu: 200m
        memory: 2Gi
      limits:
        memory: 12Gi
