apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleetserver
spec:
  version: 8.14.1
  kibanaRef:
    name: elastic-cluster
  elasticsearchRefs:
  - name: elastic-cluster
  mode: fleet
  fleetServerEnabled: true
  policyID: fleetserver
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: cluster-agent
spec:
  version: 8.14.1
  kibanaRef:
    name: elastic-cluster
  fleetServerRef:
    name: fleetserver
  mode: fleet
  policyID: cluster-agent
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
