# secure-elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-cluster
  namespace: elastic-system
spec:
  version: 8.14.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: master-nodes
      count: 1
      config:
        node.roles: ["master", "remote_cluster_client"]
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                cpu: 2
                memory: 2.5Gi
              requests:
                cpu: 1
                memory: 2Gi
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: longhorn-backup
    - name: data-nodes
      count: 1
      config:
        node.roles: ["data", "ingest", "remote_cluster_client"]
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 1
                memory: 2Gi
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: longhorn-backup


