---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: collabora
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: collabora-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .COLLABORA_USERNAME }}"
        password: "{{ .COLLABORA_PASSWORD }}"
  dataFrom:
    - extract:
        key: collabora
