---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collabora
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      code:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          code:
            env:
              extra_params: --o:ssl.termination=true --o:ssl.enable=false
              lang: de_DE
              dictionaries: de_DE en_GB en_US es_ES fr_FR
            envFrom:
              - secretRef:
                  name: collabora-secret
            image:
              repository: collabora/code
              tag: 24.04.3.1.1@sha256:5e8efa0b2ef31b9c544ed0d3d2d16a10a3ce6087eeda3771150e44baa2e2b50f
    ingress:
      code:
        enabled: true
        className: internal
        annotations:
          # external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          # nginx.ingress.kubernetes.io/server-snippet: |
            # block admin and metrics endpoint from outside by default
            # location /cool/getMetrics { deny all; return 403; }
            # location /cool/adminws/ { deny all; return 403; }
            # location /browser/dist/admin/admin.html { deny all; return 403; }
         # nginx.ingress.kubernetes.io/whitelist-source-range: |
           # 10.0.0.0/8,192.168.0.0/16
        hosts:
          - host: &host "collabora.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: ImplementationSpecific
                service:
                  identifier: code
                  port: http
        tls:
          - hosts:
              - *host
    service:
      code:
        controller: code
        ports:
          http:
            port: 9980
