---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwebui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openwebui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DATABASE_URL: "postgres://{{ .OPENWEBUI_DBUSER }}:{{ .OPENWEBUI_DBPASS }}@cnpg-openwebui-rw.ai.svc.cluster.local:5432/openwebuidb?sslmode=disable"
        WEBSOCKET_REDIS_URL: "redis://:${REDIS_HOST_PASSWORD}@dragonfly.database.svc.cluster.local:6379"
        OPENAI_API_KEY: "{{ .OPENROUTER_OPENWEBUI_API_KEY }}"
        # OAuth
        OAUTH_CLIENT_ID: "{{ .OPEN_WEBUI_OIDC_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPEN_WEBUI_OIDC_CLIENT_SECRET }}"
        WEBUI_SECRET_KEY: "{{ .OPEN_WEBUI_SECRET_KEY }}"
        # S3
        S3_ACCESS_KEY_ID: "{{ .MINIO_K8SOPENWEBUI_KEYID }}"
        S3_SECRET_ACCESS_KEY: "{{ .MINIO_K8SOPENWEBUI_SECRET }}"
  dataFrom:
    - extract:
        key: openwebui
    - extract:
        key: openrouter
    - extract:
        key: minio
