---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openwebui
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: openwebui-secret
        containers:
          open-webui:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: 0.6.13@sha256:ddc64d14ec933e8c1caf017df8a0068bece3e35acbc59e4aa4971e5aa4176a72
            env:
              CORS_ALLOW_ORIGIN: https://gpt.${SECRET_DOMAIN}
              WEBUI_URL: https://gpt.${SECRET_DOMAIN}
              ENABLE_SIGNUP: true
              ENABLE_OAUTH_SIGNUP: true
              DEFAULT_LOCALE: de
              DEFAULT_USER_ROLE: user
              DATA_DIR: /app/backend/data
              ENV: prod
              ENABLE_OLLAMA_API: false
              OPENAI_API_BASE_URL: https://openrouter.ai/api/v1
              ENABLE_RAG_WEB_SEARCH: true
              RAG_WEB_SEARCH_ENGINE: searxng
              SEARXNG_QUERY_URL: http://searxng.productivity.svc.cluster.local:8080/search?q=<query>
              ENABLE_WEBSOCKET_SUPPORT: "true"
              WEBSOCKET_MANAGER: "redis"
              OAUTH_PROVIDER_NAME: Authentik
              OAUTH_MERGE_ACCOUNTS_BY_EMAIL: false
              OPENID_PROVIDER_URL: https://id.${SECRET_DOMAIN}/application/o/openwebui/.well-known/openid-configuration
              OPENID_REDIRECT_URI: https://chat.${SECRET_DOMAIN}/oauth/oidc/callback
              OAUTH_SCOPES: openid email profile
              OAUTH_UPDATE_PICTURE_ON_LOGIN: true
              TZ: ${TIMEZONE}
              VECTOR_DB: elasticsearch
              ELASTICSEARCH_URL: http://open-webui-elasticsearch.ai.svc.cluster.local:9200
              CONTENT_EXTRACTION_ENGINE: tika
              TIKA_SERVER_URL: http://paperless-tika.productivity.svc.cluster.local:9998
            envFrom:
              - secretRef:
                  name: openwebui-secret
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                memory: 4Gi
            securityContext:
              runAsNonRoot: false
              runAsUser: 3000
              runAsGroup: 3000
              fsGroup: 3000
          elasticsearch:
            image:
              repository: elasticsearch
              tag: 9.0.1@sha256:26abc2782ee790b76df4e0806ea492967d14bcddb8c58e0eb3cc8593b363ad6c
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 4096Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              TZ: ${TIMEZONE}
              xpack.security.enabled: "false"
              discovery.type: "single-node"
              ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    service:
      open-webui:
        controller: main
        ports:
          http:
            port: 8080
      elasticsearch:
        controller: main
        ports:
          http:
            port: 9200
    ingress:
      open-webui:
        enabled: true
        className: internal
        hosts:
          - host: &host "gpt.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: open-webui
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: openwebui-pvc
        globalMounts:
          - path: /app/backend/data
