---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app eck-operator
  namespace: flux-system
spec:
  targetNamespace: elastic
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/elastic/eck/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app eck-cluster
  namespace: flux-system
spec:
  targetNamespace: elastic
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: eck-operator
  path: ./kubernetes/apps/elastic/eck/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
