---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .HASS_DBUSER }}"
        password: "{{ .HASS_DBPASS }}"
        ACCESS_KEY_ID: "{{ .MINIO_K8SPOSTGRES_KEYID }}"
        SECRET_ACCESS_KEY: "{{ .MINIO_K8SPOSTGRES_SECRET }}"
        VSCODE_TOKEN: "{{ .HASS_VSCODE_TOKEN }}"
        POSTGRES_URL: "postgresql://{{ .HASS_DBUSER }}:{{ .HASS_DBPASS }}@cnpg-home-assistant.productivity.svc.cluster.local:5432/hassdb"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: home-assistant
