---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 225
            runAsGroup: 220
            runAsNonRoot: true
            fsGroup: 220
            fsGroupChangePolicy: OnRootMismatch
        containers:
          home-assistant:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.12.5
            env:
              SECRET_RECORDER_DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: home-assistant-secret
                    key: POSTGRES_URL
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 500M
              limits:
                memory: 1000M
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.96.2
            args:
              [
                "--auth",
                "none",
                "--disable-telemetry",
                "--disable-update-check",
                "--user-data-dir",
                "/config/.vscode",
                "--extensions-dir",
                "/config/.vscode",
                "--port",
                "8080",
                "/config",
              ]
            env:
              HASS_SERVER: http://localhost:8123
              HASS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: home-assistant-secret
                    key: VSCODE_TOKEN
            resources:
              requests:
                cpu: 10m
                memory: 100M
              limits:
                memory: 500M
    service:
      home-assistant:
        controller: home-assistant
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.10.210
        ports:
          sonos:
            enabled: true
            port: 1400
          http:
            port: 8123
          code-server:
            port: 8080
    ingress:
      home-assistant:
        className: internal
        annotations:
          nginx.org/websocket-services: home-assistant
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: home-assistant
                  port: http
        tls:
          - hosts:
              - *host
      code-server:
        enabled: true
        className: internal
        hosts:
          - host: &code-host "code.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: home-assistant
                  port: code-server
        tls:
          - hosts:
              - *code-host
    persistence:
      config:
        existingClaim: home-assistant-nfs-pvc
        advancedMounts:
          home-assistant:
            home-assistant:
              - path: /config
            code-server:
              - path: /config
      # https://community.home-assistant.io/t/wth-is-going-on-with-docker-container-installs-and-third-party-integrations-that-need-python-modules/806430/6
      hack:
        type: emptyDir
        advancedMounts:
          home-assistant:
            home-assistant:
              - path: /.dockerenv
                subPath: .dockerenv
