---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: home-assistant-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NFS_SERVER}"
    path: /mnt/data/hass/
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-nfs-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: home-assistant-nfs
  resources:
    requests:
      storage: 1Mi
