apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-feature-discovery
spec:
  interval: 1h
  chart:
    spec:
      chart: *app
      version: 0.17.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
      interval: 1h
  maxHistory: 2
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    master:
      replicaCount: 1
    worker:
      config:
        core:
          sources:
            - pci
            - system
            - usb
    prometheus:
      enable: true
      scrapeInterval: 60s
