apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:qtfIqDYWTZqcX5g9ppBs831TZKmi/J33e3fZ0fZop7r81UFh,iv:r1AiLQYQI6e32eB3a2o22stfh8AQFJKRdGXi15KQ7cE=,tag:I/0h4jNXq7O0orDSyT83xQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:xj3DKDCWVHNvFRpJYCRyEjURe5cROf0mf74RcMIE+o9immpVRcWdyub0mvJuqmikW58WNv/DOuzXAjl8YtyrjOg6GdGZ6HZkNlytTuNjYV1YnynSqgv6eoy2hYvdJpX4tFJxOqFioph0Qn4gkUl3Xt8naQdZ+31S1BcKYyz2YrxwEg2snd2q4Xqv9g0s07V2icgv9XqyB/qnX9svVQBQXTuqVD+frH04hWJW3N2eNw==,iv:1h4CqS7UO/grcsUf/5M8iy2qZdkfD/GjH44BSzVVigs=,tag:07xb5yaY8xWOPWXHdOwq+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MU9NYUpOTUh6dUJYankx
            QXN4cG8vZFp5WXROS0lpRDMzU3pSWTBsVkhRCldjSmRDRHlZWHYrcDFBWkVXcksx
            U0V1UE5YRzNvTWY5RHVLTzRuZUpLT0EKLS0tIEtSdEpXaFJVWmxxMUc3eXRXNG9I
            ZHJKRUNGN1M3akwwcFkvZ2R5WnlXMXMKGbNN0GO3U0/TxG739Gzraf1wdNdZyX49
            kTZubLzK0yipd8HlvkIxqRAtfEvTuVfLwwptoqSFhGvaBjgGg/ac3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T13:15:52Z"
    mac: ENC[AES256_GCM,data:8HyzCn1JY+PFwAqjJ4c/8ZSncar4nZG0XKcgNSdNXdmT+ew6nNA+qYMOHTeM1vQ+tMbouVKPas3FjSvs306BXA23b+q7+rRuCCHYc2hBAu16TYZk4bSVID3braet9rSArlGjdVFea4PFXkWo+/BaVGsZJlbUtRWLaKz6bxbBGI8=,iv:H7V7ECjEb7/t/Y8GUz1p+TzrEIRIJfNgRga2/JyP9AQ=,tag:sfgP+fch5HQ1fcAHXZx/5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
