apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:tmSm4/wIGZmC4WCYXHuZuBu8xsjUyZ4NPJS6PD5G+k6623oz,iv:0QXP7z1zP3cyWWtzdWXBRf8l2BOzSks/hsFt8CnAV18=,tag:C0OW8RUNnCdjb8cpKXrOyQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:2SYTmmqgw9k5nLavVje/JDEpoYhgDsPX6b8ImWhm3+oHjTs76s94LNwnipH4w6NIDn4nRt2AzUTBiBVRamSZJ41oRJYoUfD6G8ix1UZwr6s7v9LAwfmKH9a8ZZD3iOxFU1C7h4w0CfX/5G5VDR7NGM9AIWWMHFj39Xt0RclZRQatvCXSu68t8FvnNe1Yw+m3P47Ip9NPGwG8uq4LqUGNC5Y8I/DZJD8PMuOdPRxKNQ==,iv:iM5L/62AFf2kj6emDXOltEBq6Sia72UE9rf9G+xiSFg=,tag:zT9uy2LPrkqXIsT3J/Kbfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRUZiVkNRa3lOU293ZmZz
            UklCNnphSnRTRHphSWdZdEozejRhMVdvSXlZClFzRjJwRDdpY2lhOXBpYWVsUVI3
            TTVMcjFXWFVlRDcvOUNCWkg1ZUdXUEEKLS0tIGY5NVlkcWExdmdibkJxM3d0RTlV
            bElEelIyZWlpaVVjNlZpa1Z3QTNZWTgK682KAwhsXC/I9MNUPJrnuJCLk85Q/ac8
            G7fyzQaDlMFm6rD8oAcZSZxjEyC3S0Aph5RI5fvURy1nGDZGaY1QHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T18:15:35Z"
    mac: ENC[AES256_GCM,data:6rcZT2z/eU7aHWAF6jN0x38YiYzpOk1/AkOqcU/xxnQ0qi6ufYVIB44PFOGSLQrDoDrWMB9r+Sc36DicbjHz9R5J0jmuQUzJfS5YARD2pHHsYq8xdb3D5pGk58ZLIVh4xWfkw9pOBnM5nCwT+96u1Xw9Hde/nDdgoh0a3lnmV5o=,iv:mqbpZ5WSipdbIihkYjy3LHGAbBbN1dvpfZ7UXbZyWuE=,tag:OvhQVATfI+KvKjEjKNlv9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
