apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Brpqj7zwKyEHO06MawAFqt2Lp2A81tUUrK6N/PPNcnKalQXX,iv:zF5s/B/sAWOsIjTCwRjCvhJcYPgklJ1OZdYcmRTKxtw=,tag:77t2GOvxGl3jqI98XhwM+A==,type:str]
    credentials.json: ENC[AES256_GCM,data:kB42qI8CYutHPsNLV4hBINQNFb1Y8MBEqiYKdi6LaMXcQcF8HfqC8FRPdjDfcuez///DbvObAUlRCR3sQ75RwN/FgOF4AJZV9oVkkDsQviNMvj8Q5i+sB0HBndvaWd2xHVAS3pHE7Bby/8RHfdBDWrWqI9fmqcQ6dP/h8t1OThhMFBu/8Tv+yoX+2prZ2tGs3okL/ALDO8vp+nk5w7mmVzxrBYr2uK6uiUBAoAA35g==,iv:VLU+HhVwQddL+4HkZrHH4QeDqfI6ZKljxdX692jidDo=,tag:C6Ag4lW8OngeoWl4izjVbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUald6TkduRHpGMGYvakxE
            QnBabmZIWVZhSFBlNU9kSmpCZDNTaml4WkNVCm52aCtLYXNBeHdtcHo2Wmd2REtW
            NUpRbVRLYjNFb0hidE9WeXBobFo1WHcKLS0tIEtKMkQwbXlZUFgwTFdQL3ZQR216
            ZzRRU2hSQVBFc25ibitUV1YzUFNNSmsKCYU7Z/06QgGnJq2cx8bSfGJPgq906aJL
            TosRxqPH+/aEZGco3+cD7HO6ld08cXpvUhP7RCzHGR32joeV694B3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T21:31:51Z"
    mac: ENC[AES256_GCM,data:sqFJadIc/sb15uoqfvm44ksJTKAig/IHPpPRP9GK7ti9gB+2tmhNQD21yPxCF6T0hrc1nrzFG9rVcizdPKTqDQO5h/oZO34bCHAam3E4fuJnbiiY8ppGn7qASPxfT284TWHAjGdxx4FOBeF+J1O4UDCl42xANPvYnzdyZpx5Hbw=,iv:PR7t/fLCDN6Gp97LjuHB1I/kf8QeE9aW24fGDrtvh+c=,tag:8q8MFxi/hcGyabUpTN5oyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
