---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: immich-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NFS_SERVER}"
    path: /mnt/data/immich/
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: immich-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-redis-data
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-basic
  resources:
    requests:
      storage: 2Gi
