---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-redis-data
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: iscsi
  resources:
    requests:
      storage: 2Gi
