---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app searxng
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          searxng:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2025.6.6-33891e5@sha256:64e7df5acb7399caafc457096082ea662639ef8742b5e37015bc1c2a9451ba0d
            command:
              - /usr/local/searxng/venv/bin/uwsgi
              - --master
              - /usr/local/searxng/.template/uwsgi.ini
            env:
              SEARXNG_BASE_URL: https://search.${SECRET_DOMAIN}
              SEARXNG_URL: https://search.${SECRET_DOMAIN}
              SEARXNG_PORT: &httpPort 8080
              UWSGI_WORKERS: "1"
            envFrom:
              - secretRef:
                  name: searxng-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /stats
                    port: *httpPort
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE
    service:
      searxng:
        controller: main
        ports:
          http:
            port: *httpPort
    ingress:
      searxng:
        className: "internal"
        annotations:
          nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
          nginx.ingress.kubernetes.io/x-forwarded-for-header: "X-Forwarded-For"
          nginx.ingress.kubernetes.io/enable-real-ip: "true"
        hosts:
          - host: search.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: searxng
                  port: http
    persistence:
      config:
        type: configMap
        name: searxng-configmap
        advancedMounts:
          main:
            searxng:
              - path: /etc/searxng/settings.yml
                subPath: settings.yml
              - path: /etc/searxng/limiter.toml
                subPath: limiter.toml
              - path: /etc/searxng/favicons.toml
                subPath: favicons.toml
      tmp:
        type: emptyDir
        advancedMounts:
          main:
            searxng:
              - path: /etc/searxng
              - path: /tmp
              - path: /var/cache/searxng/
