---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/persistentvolume-v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cnpg-immich-nfs
spec:
  capacity:
    storage: 1Mi # Size does not matter
  accessModes:
    - ReadWriteMany
  storageClassName: cnpg-immich-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NFS_SERVER}"
    path: /mnt/data/postgresql/immich
  mountOptions:
    - vers=4.2
    - nconnect=8
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnpg-immich-nfs-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: cnpg-immich-nfs
  resources:
    requests:
      storage: 1Mi
