---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pod-security.kubernetes.io/enforce: privileged
    owner: cypr0
    protection-level: high
