---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mastodon-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_PASS: "{{ .MASTODON_DB_PASSWORD }}"
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
        OTP_SECRET: "{{ .OTP_SECRET }}"
        VAPID_PRIVATE_KEY: "{{ .VAPID_PRIVATE_KEY }}"
        VAPID_PUBLIC_KEY: "{{ .VAPID_PUBLIC_KEY }}"
        MASTODON_ADMIN_USER: "{{ .MASTODON_ADMIN_USER }}"
        ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: "{{ .ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY }}"
        ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: "{{ .ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT }}"
        ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: "{{ .ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY }}"
        AWS_ACCESS_KEY_ID: "{{ .MASTODON_S3_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MASTODON_S3_SECRET_KEY }}"
        OIDC_CLIENT_ID: "{{ .MASTODON_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MASTODON_OIDC_CLIENT_SECRET }}"
        REDIS_PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
  dataFrom:
    - extract:
        key: mastodon
    - extract:
        key: dragonfly
