apiVersion: batch/v1
kind: Job
metadata:
  name: mastodon-create-admin-account
spec:
  template:
    spec:
      containers:
      - name: mastodon-create-admin-account
        image: lscr.io/linuxserver/mastodon:4.3.1
        command:
          - sh
          - -c
          - |
            echo "Waiting for Mastodon to be ready..."
            while ! curl -sf https://mastodon.${SECRET_DOMAIN}/api/v2/instance > /dev/null; do
              echo "Mastodon is not ready yet. Waiting for 5 seconds..."
              sleep 5
            done
            echo "Mastodon is ready. Checking if admin user exists..."

            if tootctl accounts search ${MASTODON_ADMIN_USER} | grep -q ${MASTODON_ADMIN_USER}; then
              echo "Admin user ${MASTODON_ADMIN_USER} already exists. Skipping creation."
            else
              echo "Admin user does not exist. Creating admin user account..."
              tootctl accounts create ${MASTODON_ADMIN_USER} --email admin@${SECRET_DOMAIN} --password ${MASTODON_ADMIN_PASSWORD} --confirmed --role Owner
            fi
        env:
        - name: DB_HOST
          value: cnpg-mastodon-rw.productivity.svc.cluster.local
        - name: DB_NAME
          value: mastodondb
        - name: DB_PORT
          value: "5432"
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: RAILS_ENV
          value: production
        - name: REDIS_HOST
          value: dragonfly.database.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: MASTODON_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: mastodon-secret
              key: MASTODON_ADMIN_USER
        - name: MASTODON_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mastodon-secret
              key: MASTODON_ADMIN_PASSWORD
        volumeMounts:
        - name: config
          mountPath: /config
      restartPolicy: OnFailure
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: mastodon-config-pvc
