apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-config-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nas-nfs-store
  resources:
    requests:
      storage: 5Gi
