apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-config-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 1Gi
