---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-mastodon
spec:
  description: Postgresql cluster for Mastodon
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  instances: 1
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 4GB
      effective_cache_size: 12GB
      maintenance_work_mem: 1GB
      checkpoint_completion_target: "0.9"
      wal_buffers: 16MB
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: 69905kB
      huge_pages: off
      min_wal_size: 1GB
      max_wal_size: 4GB
      max_worker_processes: "6"
      max_parallel_workers_per_gather: "3"
      max_parallel_workers: "6"
      max_parallel_maintenance_workers: "3"
  bootstrap:
    initdb:
      database: ${MASTODON_DB_NAME}
      owner: ${MASTODON_DB_USER}
      secret:
        name: mastodon-db-secret
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  # Bootstrap to recover from an existing backup
  # Note: previousCluster needs to be set to the name of the previous cluster when recovering from an existing cnpg cluster.
  # bootstrap:
  #   recovery:
  #     source: &previousCluster mastodon-postgres16-v1
  backup:
    retentionPolicy: 7d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://k8s-cluster-postgres/mastodon/
      endpointURL: ${AWS_ENDPOINT_URL}
      serverName: &currentCluster mastodon-postgres16-v1
      s3Credentials:
        accessKeyId:
          name: mastodon-db-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: mastodon-db-secret
          key: SECRET_ACCESS_KEY
 # Note: externalClusters is needed when recovering from an existing cnpg cluster
 #  externalClusters:
 #   - name: *previousCluster
 #     barmanObjectStore:
 #       <<: *barmanObjectStore
 #       serverName: *previousCluster
