---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mastodon-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mastodon-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .MASTODON_DB_USER }}"
        password: "{{ .MASTODON_DB_PASSWORD }}"
        ACCESS_KEY_ID: "{{ .ACCESS_KEY_ID }}"
        SECRET_ACCESS_KEY: "{{ .SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: mastodon
    - extract:
        key: service-k8s-cluster-postgres
