---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    webhook:
      enabled: true
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 100Mi
          ephemeral-storage: 200Mi
