---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      nfs-server:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          nfs-server:
            env:
              NFS_DIR: /nfs-share
              NFS_DOMAIN: 192.168.40.0/24,10.69.0.0/16
              NFS_OPTION: fsid=0,ro,sync,insecure,all_squash,anonuid=65534,anongid=65534,no_subtree_check,nohide
            image:
              repository: gists/nfs-server
              tag: 12.6.4@sha256:965b1437bce8b09c508df1006c5b919f7e82486edd68f296edae045302eeab65
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      nfs-server:
        controller: nfs-server
        ports:
          nfs:
            port: 2049
    persistence:
      nfs-share:
        enabled: true
        existingClaim: nfs-server-pvc
        globalMounts:
          - path: /nfs-share
