---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-basic
  resources:
    requests:
      storage: 5Gi
