apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
  data:
    - secretKey: adminUser
      remoteRef:
        key: grafana
        property: GRAFANA_ADMIN_USER
    - secretKey: adminPass
      remoteRef:
        key: grafana
        property: GRAFANA_ADMIN_PASSWORD
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: grafana
        property: GRAFANA_OPENID_CLIENT_ID
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: grafana
        property: GRAFANA_OPENID_CLIENT_SECRET

