---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mixpost-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mixpost-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .MIXPOST_DB_USERNAME }}"
        password: "{{ .MIXPOST_DB_PASSWORD }}"
        ACCESS_KEY_ID: "{{ .MINIO_K8SPOSTGRES_KEYID }}"
        SECRET_ACCESS_KEY: "{{ .MINIO_K8SPOSTGRES_SECRET }}"
  dataFrom:
    - extract:
        key: mixpost
    - extract:
        key: minio
