---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: longhorn-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .MINIO_K8SLONGHORN_KEYID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_K8SLONGHORN_SECRET }}"
        AWS_ENDPOINTS: "{{ .MINIO_SERVICE_ENDPOINT }}"
  dataFrom:
    - extract:
        key: minio
