---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: minio
      namespace: storage
    - name: external-secrets
      namespace: security

  values:
    csi:
      attacherReplicaCount: 3
      provisionerReplicaCount: 3
      resizerReplicaCount: 3
      snapshotterReplicaCount: 3
    longhornUI:
      replicas: 1
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Delete
      recurringJobSelector:
        enable: false
    monitoring:
      enabled: true
      createPrometheusRules: true
    defaultSettings:
      backupTarget: s3://k8s-longhorn@eu-central-1/
      backupTargetCredentialSecret: longhorn-secret
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      restoreVolumeRecurringJobs: true
      defaultLonghornStaticStorageClass: longhorn-backup
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      orphanAutoDeletion: true
      autoCleanupSystemGeneratedSnapshot: true
      autoCleanupRecurringJobBackupSnapshot: true
      snapshotDataIntegrity: enable
      snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: false
      snapshotDataIntegrityCronjob: "0 4 * * *"
      fastReplicaRebuildEnabled: true
      removeSnapshotsDuringFilesystemTrim: true
      v1DataEngine: true
      v2DataEngine: false
      allowCollectingLonghornUsageMetrics: false
      freezeFilesystemForSnapshot: enabled
      autoCleanupSnapshotWhenDeleteBackup: true
      rwxVolumeFastFailover: true
    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.${SECRET_DOMAIN}
      tls: true
    metrics:
      serviceMonitor:
        enabled: true
