apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-templates
data:
  mail-password-reset.html: |
    {% extends "email/base.html" %}
    {% load i18n %}
    {% load humanize %}

    {% block content %}
    <tr>
        <td class="alert alert-success">
            Passwort-Zurücksetzung bei {{ tenant.branding_title }}
        </td>
    </tr>

    <tr><td height="15"></td></tr>

    <tr>
        <td class="content-wrap">
            <p>Hallo {{ user.name|default:user.username }},</p>

            <p>
                Du hast kürzlich angefragt, das Passwort für Deinen Zugang zu <strong>{{ tenant.branding_title }}</strong> zu ändern.
            </p>

            <p>
                Klicke auf den folgenden Button, um ein neues Passwort festzulegen:
            </p>

            <table
                role="presentation"
                border="0"
                cellpadding="0"
                cellspacing="0"
                class="btn btn-primary"
            >
                <tbody>
                    <tr>
                        <td align="center">
                            <a
                                id="confirm"
                                href="{{ url }}"
                                rel="noopener noreferrer"
                                target="_blank"
                            >Passwort zurücksetzen</a>
                        </td>
                    </tr>
                </tbody>
            </table>

            <p>
                Der Link ist gültig für <strong>{{ expires|naturaltime }}</strong>.
            </p>

            <p>
                Wenn Du diese Anfrage nicht gestellt hast, kannst Du diese E-Mail ignorieren.
            </p>

            <p>Viele Grüße<br />
            Dein {{ tenant.branding_title }}-Team</p>
        </td>
    </tr>
    {% endblock %}

  mail-account-confirmation.html: |
    {% extends "email/base.html" %}
    {% load i18n %}
    {% load humanize %}

    {% block content %}
    <tr>
        <td class="alert alert-info">
            Konto bestätigen bei {{ tenant.branding_title }}
        </td>
    </tr>

    <tr><td height="15"></td></tr>

    <tr>
        <td class="content-wrap">
            <p>Hallo {{ user.name|default:user.username }},</p>

            <p>
                vielen Dank für Deine Registrierung bei <strong>{{ tenant.branding_title }}</strong>.
            </p>

            <p>
                Bitte bestätige Dein Konto, indem Du auf den folgenden Button klickst:
            </p>

            <table
                role="presentation"
                border="0"
                cellpadding="0"
                cellspacing="0"
                class="btn btn-primary"
            >
                <tbody>
                    <tr>
                        <td align="center">
                            <a href="{{ url }}" target="_blank" rel="noopener noreferrer">
                                Konto bestätigen
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>

            <p>
                Der Link ist gültig für <strong>{{ expires|naturaltime }}</strong>.
            </p>

            <p>
                Solltest Du Dich nicht bei uns registriert haben, kannst Du diese E-Mail einfach ignorieren.
            </p>

            <p>Viele Grüße<br />
            Dein {{ tenant.branding_title }}-Team</p>
        </td>
    </tr>
    {% endblock %}

  mail-invitation.html: |
    {% extends "email/base.html" %}
    {% load i18n %}
    {% load humanize %}

    {% block content %}
    <tr>
        <td class="alert alert-info">
            Einladung zu {{ tenant.branding_title }}
        </td>
    </tr>

    <tr><td height="15"></td></tr>

    <tr>
        <td class="content-wrap">
            <p>Hallo,</p>

            <p>
                Du wurdest eingeladen, Dich bei <strong>{{ tenant.branding_title }}</strong> zu registrieren.
            </p>

            <p>
                Nutze bitte den folgenden Button, um Dein Konto zu erstellen:
            </p>

            <table
                role="presentation"
                border="0"
                cellpadding="0"
                cellspacing="0"
                class="btn btn-primary"
            >
                <tbody>
                    <tr>
                        <td align="center">
                            <a href="{{ url }}" target="_blank" rel="noopener noreferrer">
                                Einladung annehmen
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>

            <p>
                Diese Einladung ist gültig bis <strong>{{ expires|naturaltime }}</strong>.
            </p>

            <p>Viele Grüße<br />
            Dein {{ tenant.branding_title }}-Team</p>
        </td>
    </tr>
    {% endblock %}

  mail-account-created.html: |
    {% extends "email/base.html" %}
    {% load i18n %}

    {% block content %}
    <tr>
        <td class="alert alert-success">
            Konto erfolgreich erstellt – Willkommen bei {{ tenant.branding_title }}
        </td>
    </tr>

    <tr><td height="15"></td></tr>

    <tr>
        <td class="content-wrap">
            <p>Hallo {{ user.name|default:user.username }},</p>

            <p>
                Dein Benutzerkonto bei <strong>{{ tenant.branding_title }}</strong> wurde erfolgreich erstellt.
            </p>

            <p>
                Du kannst Dich ab sofort mit Deinen Zugangsdaten anmelden.
            </p>

            <p>Viele Grüße<br />
            Dein {{ tenant.branding_title }}-Team</p>
        </td>
    </tr>
    {% endblock %}
