apiVersion: v1
kind: ConfigMap
metadata:
    name: authentik-templates
data:
    custom-mail.html: |
      {% extends "email/base.html" %}
      {% load i18n %}
      {% load humanize %}

      {% block content %}
      <tr>
          <td class="alert alert-success">
              Hallo {{ user.username }},
          </td>
      </tr>
      <tr>
          <td class="content-wrap">
              <table width="100%" cellpadding="0" cellspacing="0">
                  <tr>
                      <td class="content-block">
                          Du hast kürzlich angefragt, das Passwort für Deinen authentik-Zugang zu ändern.
                          Klicke auf den folgenden Button, um ein neues Passwort festzulegen:
                      </td>
                  </tr>
                  <tr>
                      <td class="content-block">
                          <table
                              role="presentation"
                              border="0"
                              cellpadding="0"
                              cellspacing="0"
                              class="btn btn-primary"
                          >
                              <tbody>
                                  <tr>
                                      <td align="center">
                                          <table
                                              role="presentation"
                                              border="0"
                                              cellpadding="0"
                                              cellspacing="0"
                                          >
                                              <tbody>
                                                  <tr>
                                                      <td>
                                                          <a
                                                              id="confirm"
                                                              href="{{ url }}"
                                                              rel="noopener noreferrer"
                                                              target="_blank"
                                                          >Passwort zurücksetzen</a>
                                                      </td>
                                                  </tr>
                                              </tbody>
                                          </table>
                                      </td>
                                  </tr>
                              </tbody>
                          </table>
                      </td>
                  </tr>
                  <tr>
                      <td class="content-block">
                          Wenn Du keine Änderung deines Passworts angefordert hast, kannst Du diese E-Mail ignorieren.
                          Der Link ist gültig für {{ expires|naturaltime }}.
                      </td>
                  </tr>
              </table>
          </td>
      </tr>
      {% endblock %}
