apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleetserver
spec:
  version: 8.14.1
  kibanaRef:
    name: eck-cluster
  elasticsearchRefs:
  - name: eck-cluster
  mode: fleet
  fleetServerEnabled: true
  policyID: fleet-server
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
