apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eck-cluster
spec:
  version: 8.14.1
  count: 1
  elasticsearchRef:
    name: eck-cluster
    namespace: database
  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://eck-cluster-es-ingest-nodes.database.svc.cluster.local:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://eck-cluster-fleetserver-agent.datanase.svc.cluster.local:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server Policy
        id: fleet-server
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
