apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:egyx0Jnv/3fcdu5hiqhm551aeq4S/n+0OqpQXVhxjX2lu6NmHIGyzQ==,iv:u4o0ukxR0c0vlmqOZ0i9MskFn+nbyM3C5xg5SFhcPTs=,tag:MIuCbvdlF03+UIyoQAP3Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTFA2WFc5dERBdkozYVFt
            WFRhWE1HWlNHc01Pc1VPMDZtRVpCVEt1cng4CmxGVlNUNUplN2tNd2hqQ1Ivb09C
            aXIvR2RYZG5qdXNyN3hVelRFd2dEblUKLS0tIE5oUUZ1L3RhNmxDRi9JRXkxN2Fn
            TklLWmFmcTh6WDMxQThsN0NuanVGa1EKsXIWjDgkWS3yk7+DW1qaGQEBmFKfHbqb
            L9i8p7MLe3Pi7xDJrNLJikBpY0rYegkefpMRUk/zIobSIWjtSj1VXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T18:15:35Z"
    mac: ENC[AES256_GCM,data:xp4OIUYxM4CDjzncaNtrea34UXoRkT0YOJid5UNf80CQy3OvYV82i3nZ+dkaAt5ZNoEz0b/tYhiO1hlT5gu9p3hcRsWV1M0sgQpH1XF/Xyj7Gs+eY6dVwwj/HagM+cfy8j9loUXvA5XY7GCWxo8PfIeLOsHH1hXwj7ql+qgN81o=,iv:jjZW2oaIo9NOSSwqoExLK7AxIE5HsbhMPb2xNg5knZs=,tag:X2zfRKvI68+hFLy2WdO0sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
