apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:TxLoGEQE1/7nIQhshanle/KFBZ9ObdDug04SbjwttPw+ecGlGj/t9Q==,iv:aqSCUnUQiHP6ds7FAU2SwPIo+D7wGcey98kgHAJDb0A=,tag:VhKpTYkYFb24ffh6PDg9FA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OWtrb1RUWTBlMVlkUGdV
            RGpWMGtOYlUveVdPTEVUL3VvN0poZjBWV0d3CncxSEFxckFqVGUyWFF6REFsdFYw
            R1IyS3N2WHpHY2J0SnhqUm9MUWhDWEUKLS0tIFhlc1FiaTFvZHcwTThDYXBJY2pw
            Zm9SY25NTUUyczdPaUp3azZLZjZPUWcKXhJ39P+fhaDRm9KXRet0rYqTwVu8NND2
            PG4mVTxwSeXeLs9xc8xz9+qhv7UKlSiDEPrjhQvI+pUyln0DI8pHPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T21:31:51Z"
    mac: ENC[AES256_GCM,data:ifIvw3MJ9ofoTi+PrKUiCJaN/kXWv2oXBe6v/Iq7JZMjPQAfccNDEKlD/+TxRlONLzJPZmNAsnQQxVgPQg09N/2KSx8GYTXxnglp5rFbUHAQfcQx5CXg+XcAh5fnEENEwZvnDY+xykeqZkKNDKa1ohszo6wXVzXv0EqJhdnB7/w=,iv:cugaSA+gnQ48V3iLw1ivLEX8/CgTOsctAIXPNQK89mU=,tag:h8QTMUrndFLMYV8z0RyucQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
