apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:NlCpDOZ8hoX1dzAkfM4VMTNpbpWBmJdPQUFWM4G65bT/hSrq9ih0NQ==,iv:OmKfMRGMEeWD5Sp6Z8voj6VZGDGeVaKSnp1Ir/2FpFQ=,tag:8Wld6MV6SaW18PZpEyHPGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSHpCbFE1UlRsLzgrSFN4
            amRLS0tXWG9pbGs0NkwyOFJ1aUp2VWxzTjFzCjV5UklkbVkzejR0djRoRzErbXRD
            Y2hQWXFucytEZVErWEN4c0p6ZkovWFUKLS0tIEQ1NXBkRXRXWHNPcEpsSHN3MUUz
            Uk04ODVaT2g5cDNhczg1VFk2N2poaWcKgjwEldA4s9B8CKTNsrjaAvIgLucUpkNf
            MNoVngF87lVYAtezkf9jYLxG6654Ywz1YejNNrD9dEjrE52wTMZoeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T13:15:52Z"
    mac: ENC[AES256_GCM,data:zO7UFDmM3GECDF/5kimaTJO6GYPkqedZiRqq4/ugPJwsWlGTx4EviTtsXjqQAbx0obi5CeXUWhqzsDfyzgRYR3v/QPhgTmEsto+nMu2K8iomO8L/ES/fY0eZwzLGdtcmqk2OSluJ9klKmNrNqmkVzhWsUbN9ygc8eYLKpr6ifLM=,iv:6qiq46g6rtp9EnN4xFWlPQGEqfkPclflo+VFTfBnLm8=,tag:HDh6i1EjVuNmqrI3AKTwfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
