---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: automad-portfolio
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          automad-portfolio:
            image:
              repository: automad/automad
              tag: 2.0.0-alpha.16@sha256:9199e527760608350cd4fc194fc7acfe586ff3deb15630de7119ebc223ced1a4
            securityContext:
              runAsUser: 0
              runAsGroup: 220
              runAsNonRoot: false
              fsGroup: 220
              fsGroupChangePolicy: OnRootMismatch
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 128M
              limits:
                memory: 256M
    service:
      automad-portfolio:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      automad-portfolio:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        hosts:
          - host: &host "portfolio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: automad-portfolio
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: www-nfs-pvc
        advancedMounts:
          main:
            automad-portfolio:
              - path: /app
                subPath: portfolio
                readOnly: false
