---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTCLOUD_ADMIN_USER: "{{ .NEXTCLOUD_ADMIN_USERNAME }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        NEXTCLOUD_TOKEN: "{{ .NEXTCLOUD_TOKEN }}"
        POSTGRES_PASSWORD: "{{ .NEXTCLOUD_POSTGRESQL_PASSWORD }}"
        OBJECTSTORE_S3_KEY: "{{ .NEXTCLOUD_S3_ACCESS_KEY }}"
        OBJECTSTORE_S3_SECRET: "{{ .NEXTCLOUD_S3_SECRET_KEY }}"
        OBJECTSTORE_S3_BUCKET: "{{ .NEXTCLOUD_S3_BUCKET }}"
        OBJECTSTORE_S3_REGION: "eu-central-2"
        OBJECTSTORE_S3_HOST: "{{ .NEXTCLOUD_S3_HOSTNAME }}"
        NEXTCLOUD_SMTP_HOST: "${GLOBAL_SMTP_HOST}"
        NEXTCLOUD_SMTP_USERNAME: ""
        NEXTCLOUD_SMTP_PASSWORD: ""
        NEXTCLOUD_POSTGRESQL_HOST: "cnpg-nextcloud-rw.productivity.svc.cluster.local"
        NEXTCLOUD_POSTGRESQL_DB_NAME: "{{ .NEXTCLOUD_POSTGRESQL_DB_NAME }}"
        NEXTCLOUD_POSTGRESQL_USERNAME: "{{ .NEXTCLOUD_POSTGRESQL_USERNAME }}"
        NEXTCLOUD_POSTGRESQL_PASSWORD: "{{ .NEXTCLOUD_POSTGRESQL_PASSWORD }}"
  dataFrom:
    - extract:
        key: nextcloud
