---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    controllers:
      nextcloud:
        containers:
          app:
            image:
              repository: nextcloud
              tag: 29.0.1-apache
            probes:
              startup:
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 30
            env:
              TZ: "${TIMEZONE}"
              REDIS_HOST: "dragonfly.database.svc.cluster.local"
              SMTP_HOST: "${GLOBAL_SMTP_HOST}"
              SMTP_PORT: "25"
              SMTP_AUTHTYPE: "PLAIN"
              MAIL_FROM_ADDRESS: "admin@${SECRET_DOMAIN}"
              OVERWRITEPROTOCOL: "https"
              OVERWRITEHOST: "cloud.${SECRET_DOMAIN}"
              POSTGRES_HOST: "cnpg-nextcloud-rw.productivity.svc.cluster.local"
              POSTGRES_DB: "${NEXTCLOUD_DB_NAME}"
              POSTGRES_USER: "${NEXTCLOUD_DB_USER}"
              NEXTCLOUD_TRUSTED_DOMAINS: "cloud.${SECRET_DOMAIN} id.${SECRET_DOMAIN} collabora.{SECRET_DOMAIN} localhost"
              NEXTCLOUD_INIT_HTACCESS: "true"
              PHP_UPLOAD_LIMIT: "16G"
              TRUSTED_PROXIES: "10.69.0.0/16 10.96.0.0/16 192.168.0.0/16 127.0.0.1"
            envFrom:
              - secretRef:
                  name: nextcloud-secret
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/proxy-body-size: "10G"
          nginx.ingress.kubernetes.io/proxy-buffering: "off"
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/server-snippet: |-
            server_tokens off;
            proxy_hide_header X-Powered-By;
            rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
            rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
            rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
            rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
            location = /.well-known/carddav {
              return 301 $scheme://$host/remote.php/dav;
            }
            location = /.well-known/caldav {
              return 301 $scheme://$host/remote.php/dav;
            }
            location = /robots.txt {
              allow all;
              log_not_found off;
              access_log off;
            }
            location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
              deny all;
            }
            location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
              deny all;
            }
        hosts:
          - host: &host "cloud.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: nextcloud-pvc
        globalMounts:
          - path: /var/www/html
      settings:
        type: configMap
        name: nextcloud-user-config
        globalMounts:
          - path: /var/www/html/config/custom.config.php
            subPath: custom.config.php
            readOnly: true
