apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 6.1.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    image:
      repository: nextcloud
      tag: 30.0.1-fpm-alpine
      flavor: fpm-alpine
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret nextcloud-secret
    replicaCount: 3
    nextcloud:
      podSecurityContext:
        supplementalGroups:
          - 82
          - 220
        fsGroupChangePolicy: OnRootMismatch
      SecurityContext:
        runAsUser: 222
        runAsGroup: 220
        fsGroup: 220
        readOnlyRootFilesystem: false
        supplementalGroups:
          - 82
          - 220
      extraEnv:
        - name: REDIS_HOST
          value: dragonfly.database.svc.cluster.local
        - name: REDIS_HOST_PORT
          value: "6379"
      strategy:
         type: RollingUpdate
      host: &host cloud.${SECRET_DOMAIN}
      existingSecret:
        enabled: true
        secretName: *secret
        usernameKey: NEXTCLOUD_ADMIN_USER
        passwordKey: NEXTCLOUD_ADMIN_PASSWORD
        tokenKey: NEXTCLOUD_TOKEN
        smtpHostKey: NEXTCLOUD_SMTP_HOST
        smtpUsernameKey: NEXTCLOUD_SMTP_USERNAME
        smtpPasswordKey: NEXTCLOUD_SMTP_PASSWORD
      mail:
        enabled: true
        fromAddress: admin
        domain: ${SECRET_DOMAIN}
        smtp:
          port: 465
          timeout: 30
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' =>
            array(
               0 => '10.69.0.0/16',
               1 => '10.96.0.0/16',
               2 => '127.0.0.1',
               3 => '192.168.0.0/16',
            ),
            'forwarded_for_headers' =>
            array (
              0 => 'HTTP_X_FORWARDED_FOR',
            ),
            'trusted_domains' =>
            array(
               0 => 'cloud.${SECRET_DOMAIN}',
               1 => 'id.${SECRET_DOMAIN}',
               2 => 'collabora.${SECRET_DOMAIN}',
               3 => 'localhost',
            ),
            'allow_local_remote_servers' => true,
            'overwriteprotocol' => 'https',
          );
        user.config.php: |-
          <?php
          $CONFIG = array (
            'default_language' => 'de',
            'default_locale' => 'de_DE',
            'default_phone_region' => 'DE',
            'default_timezone' => 'Europe/Berlin',
            'maintenance_window_start' => 1,
            'trashbin_retention_obligation' => 'auto, 30',
            'auth.bruteforce.protection.enabled' => true,
            'allow_user_to_change_display_name' => false,
            'forbidden_filenames' => array (
               0 => '.htaccess',
               1 => 'Thums.db',
               2 => 'thumbs.db',
               ),
            'enable_previews' => true,
            'enabledPreviewProviders' => array (
                0 => 'OC\\Preview\\PNG',
                1 => 'OC\\Preview\\JPEG',
                2 => 'OC\\Preview\\GIF',
                3 => 'OC\\Preview\\BMP',
                4 => 'OC\\Preview\\XBitmap',
                5 => 'OC\\Preview\\Movie',
                6 => 'OC\\Preview\\PDF',
                7 => 'OC\\Preview\\MP3',
                8 => 'OC\\Preview\\TXT',
                9 => 'OC\\Preview\\MarkDown',
                10 => 'OC\\Preview\\HEIC',
                11 => 'OC\\Preview\\Movie',
                12 => 'OC\\Preview\\MKV',
                13 => 'OC\\Preview\\MP4',
                14 => 'OC\\Preview\\AVI',
                ),
            'filesystem_check_changes' => 0,
            'filelocking.enabled' => true,
            'integrity.check.disabled' => false,
            'preview_max_x' => 1024,
            'preview_max_y' => 768,
            'preview_max_scale_factor' => 1,
            'quota_include_external_storage' => false,
            'share_folder' => '/Freigaben',
            'skeletondirectory' => '',
          );
        bulkupload.config.php: |-
          <?php
          $CONFIG = array (
            'bulkupload.enabled' => false,
          );
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
    extraVolumes:
      - name: paperless-nfs
        nfs:
          server: "${SECRET_NFS_SERVER}"
          path: "/mnt/data/paperless"
          readOnly: false
    extraVolumeMounts:
      - name: paperless-nfs
        mountPath: "/mnt/data/paperless"
    datadir: /nc_data
    persistence:
      enabled: true
      existingClaim: nextcloud-pvc
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          add_header X-Robots-Tag "noindex, nofollow";
          more_set_headers "X-Frame-Options: SAMEORIGIN";
          more_set_headers "X-Xss-Protection: 1; mode=block";
          more_set_headers "X-Permitted-Cross-Domain-Policies: none";
          more_set_headers "Content-Security-Policy "default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self';";
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: /
      pathType: Prefix
      tls: [hosts: [*host]]
    nginx:
      enabled: true
      image:
        repository: nginx
        tag: 1.27-alpine
      config:
        default: true
      SecurityContext:
        runAsUser: 222
        runAsGroup: 220
        fsGroup: 220
        readOnlyRootFilesystem: false
        supplementalGroups:
          - 82
          - 220
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: false
      type: postgresql
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: *secret
        hostKey: NEXTCLOUD_POSTGRESQL_HOST
        databaseKey: NEXTCLOUD_POSTGRESQL_DB_NAME
        usernameKey: NEXTCLOUD_POSTGRESQL_USERNAME
        passwordKey: NEXTCLOUD_POSTGRESQL_PASSWORD
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    cronjob:
      enabled: true
      SecurityContext:
        runAsUser: 222
        runAsGroup: 220
        fsGroup: 220
        readOnlyRootFilesystem: false
        supplementalGroups:
          - 82
          - 220
