---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./authentik/ks.yaml
  - ./external-secrets/ks.yaml
  - ./onepassword-connect/ks.yaml
  # - ./wazuh/ks.yaml
