---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mastodon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mastodon-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MASTODON_ADMIN_USER: "{{ .MASTODON_ADMIN_USER }}"
        MASTODON_SMTP_SERVER: "192.168.10.1"
        MASTODON_SMTP_PASSWORD: ""
        MASTODON_SMTP_LOGIN: ""
        OTP_SECRET: "{{ .OTP_SECRET }}"
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
        VAPID_PRIVATE_KEY: "{{ .VAPID_PRIVATE_KEY }}"
        VAPID_PUBLIC_KEY: "{{ .VAPID_PUBLIC_KEY }}"
        MASTODON_DB_PASSWORD: "{{ .MASTODON_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: mastodon
