---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "s3-${SECRET_DOMAIN/./-}"
spec:
  secretName: "s3-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "s3.${SECRET_DOMAIN}"
  dnsNames:
    - "s3.${SECRET_DOMAIN}"
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Always
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "minio-${SECRET_DOMAIN/./-}"
spec:
  secretName: "minio-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "minio.${SECRET_DOMAIN}"
  dnsNames:
    - "minio.${SECRET_DOMAIN}"
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Always
