---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minio-secret
    template:
      engineVersion: v2
      data:
        rootUser: "{{ .MINIO_ROOT_USER }}"
        rootPassword: "{{ .MINIO_ROOT_PASSWORD }}"
        mastodon-user: "{{ .MASTODON_S3_SECRET_KEY }}"
        postgres-user: "{{ .MINIO_K8SPOSTGRES_SECRET }}"
        velero-user: "{{ .MINIO_K8SVELERO_SECRET }}"
        openwebui-user: "{{ .MINIO_K8SOPENWEBUI_SECRET }}"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: mastodon
