---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-secret
    creationPolicy: Owner
  data:
    - secretKey: pushover_api_token
      remoteRef:
        key: pushover
        property: ALERTMANAGER_PUSHOVER_API_TOKEN
    - secretKey: pushover_api_userkey
      remoteRef:
        key: pushover
        property: PUSHOVER_USER_KEY
