---
web:
  port: $${WEB_PORT}
storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
alerting:
  pushover:
    title: Gatus
    application-token: $${PUSHOVER_TOKEN}
    user-key: $${PUSHOVER_USER_KEY}
    priority: 1
    resolved-priority: 0
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:

  - name: immich
    group: applications
    url: https://media.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
      - "[BODY].includes('Immich')"
    alerts:
      - type: pushover
        description: Immich health-check failed

  - name: nextcloud
    group: applications
    url: https://cloud.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
      - "[BODY].includes('Nextcloud')"
    alerts:
      - type: pushover
        description: Nextcloud health-check failed

  - name: mastodon
    group: applications
    url: https://social.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
      - "[BODY].includes('Mastodon')"
    alerts:
      - type: pushover
        description: Mastodon health-check failed

  - name: authentik
    group: applications
    url: https://id.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
      - "[BODY].includes('Authentik')"
    alerts:
      - type: pushover
        description: Authentik health-check failed
