---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: script/helm/garage
      version: 0.7.0
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    garage:
      replicationMode: "1"
      rpcSecret: ${GARAGE_RPC_SECRET}
      s3:
        api:
          region: "eu-central-1"
    deployment:
      replicaCount: 1
    persistence:
      meta:
        storageClass: "nas-nfs-store"
        size: 1Gi
      data:
        storageClass: "nas-nfs-store"
        size: 300Gi
    ingress:
      s3:
        api:
          enabled: true
          className: "external"
          annotations:
            external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
            nginx.ingress.kubernetes.io/proxy-body-size: 500m
          hosts:
            - host: &host s3-api.${SECRET_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
          tls: [hosts: [*host]]
    monitoring:
      metrics:
        serviceMonitor:
          enabled: true
    podSecurityContext:
      fsGroup: 3000
      runAsGroup: 3000
      runAsUser: 3000
