---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: garage
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: garage
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    garage:
      # Use only 2 replicas per object
      replicationMode: "1"

    # Start 4 instances (StatefulSets) of garage
    deployment:
      replicaCount: 3

    # Override default storage class and size
    persistence:
      meta:
        storageClass: "openebs-hostpath"
        size: 100Mi
      data:
        storageClass: "openebs-hostpath"
        size: 1Gi

    ingress:
      s3:
        api:
          enabled: true
          className: "external"
          annotations:
            external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
            nginx.ingress.kubernetes.io/proxy-body-size: 500m
          hosts:
            - host: &host s3-api.${SECRET_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
          tls: [hosts: [*host]]
