---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: script/helm/garage
      version: 0.7.0
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    garage:
      garageTomlString: |
        metadata_dir = "/mnt/meta"
        data_dir = "/mnt/data"

        db_engine = "lmdb"

        block_size = "1M"

        replication_mode = "1"

        compression_level = 1

        metadata_auto_snapshot_interval = "6h"

        rpc_bind_addr = "[::]:3901"
        rpc_secret = "${GARAGE_RPC_SECRET}"

        [kubernetes_discovery]
        namespace = "storage-system"
        service_name = "garage"
        skip_crd = false

        [s3_api]
        s3_region = "eu-central-1"
        api_bind_addr = "[::]:3900"
        root_domain = ".s3-api.${SECRET_DOMAIN}"

        [admin]
        api_bind_addr = "[::]:3903"
        admin_token = "${GARAGE_ADMIN_TOKEN}"
    deployment:
      replicaCount: 1
    image:
      repository: dxflrs/amd64_garage
      tag: v1.1.0@sha256:fe798f1dd55025c9c8fc8da86c49c17ac67b776930d3b9e9981f7876c921519f
      pullPolicy: IfNotPresent
    persistence:
      meta:
        storageClass: "nas-nfs-store"
        size: 1Gi
      data:
        storageClass: "nas-nfs-store"
        size: 300Gi
    ingress:
      s3:
        api:
          enabled: true
          className: "external"
          annotations:
            external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
            nginx.ingress.kubernetes.io/proxy-body-size: 500m
          hosts:
            - host: &api s3-api.${SECRET_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
          tls: [hosts: [*api]]
    monitoring:
      metrics:
        enabled: true
    podSecurityContext:
      fsGroup: 3000
      runAsGroup: 3000
      runAsUser: 3000
