---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./alertmanager/ks.yaml
 # - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./node-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
