apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:MMLpoDSMsqmcgw==,iv:XStCohykb10uYuU/jmgSImnEm7U3tlpKArWtb92BxSw=,tag:4lXj0WtmBQ6tdIhOG9ceEQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:fcpcBBoJf6C2JPxjDRa5,iv:OCucdakIduuLIkwEqEibRpUvrI1SFDflQR8Yx2FaJw4=,tag:gmVHiwoeA3CXuWlJcVqj3Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KqfYKzFepJ/q0C6hFWiD1YVHrOKZU/yai292ad49EuqCzLPw,iv:lfS/tZb1vSBftPmvTIHZstmJkRoixNUBQFvY2d8238E=,tag:/vQYG74V+UdARgc7vdJn8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcVVSTnB6MXJVRy83WnAx
            UVJJeEk5NHJRMHN5a2ljYVQ0ajVqNTVGaVJVCnlZWDE4c0NCWnIwNUpMRFUxTHFu
            aUpSZmRmZVQ4WWpWREFpT3pxTEt4dm8KLS0tIEVrNU1mNWlGaytzWVZpSGNpTXRF
            TmNxM0E2SENMZDhSY1JWaFBFdnRaVzAK4Tj8UOYvWskmMREj6AZlXTBNwvqyCKQ6
            fAOGO1KWNT1T+/DtnCXNsuA+pM1UAeIynxF5d3hnFl6wymmdjEgwCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T21:31:51Z"
    mac: ENC[AES256_GCM,data:LP2z/8CKLf+BDrJySDrMV4qHEyfr5IodDpEBs5iz0x7rbLJIW0mJ/n/LnJCt6+pOm3Re63LxqdZhbw6rWXithzlauJ20pzcQQn6njlMvOaar+b2Pp4rOzfufkqgsTaQwBbT640QmkRsHpK3AmriOX5DiEli7BnMQSBeoCABiBhs=,iv:zv4KM8igP95MRKjF3zxj/BCXpzYG3TRIlpwCGi0QO7g=,tag:BN2gywuZFpdNu7X9ZucHhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
