apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dSv4JBRNVwr3Xg==,iv:Y8WKRrujJub7Rfcam3t9LBJDwbml5sB4uJwF6X6dyW0=,tag:HLXqwh8Mrmr0dVxmdtidJg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mLIiaajz+fMiV2eTlD8+,iv:fqbX0jYazz1OIDC71LNBKPKZkG2Zw/cgNJ+agmBrG74=,tag:zxcho+0Lw+4yvkKVppBNMg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:GRQ/OmOtQalQUMamhh0jwW8sJXV+YkLB7rN4vjJoqn+ifQF4,iv:V5cxDVrAfBEPDzx8hFDcWfuKWSMLrnlyLpWWrvs7X8c=,tag:oCtV7x/EdrMg8gfKrhsX0Q==,type:str]
    AWS_ENDPOINT_URL: ENC[AES256_GCM,data:lcwBE9DOuSHJtGCf0WneQIn5rGwbuO8cpRwoZUzAqA0Y3mxWWw==,iv:hV0WoCgJtrbsIt2RZDX9fHEpY564zKd8aGY8O3teUbQ=,tag:HOmkfRdXfyonLZEL6yA0lQ==,type:str]
    SECRET_IPV4_GATEWAY: ENC[AES256_GCM,data:46XuylLhT1Fw3gvGa8cRULBT,iv:5j1Fftnja1wfLYyI5xSAYtxUKUxgF66pOv54lMqyIMo=,tag:1YB5D0pDpl0f640GUzMnEg==,type:str]
    AUTHENTIK_DB_NAME: ENC[AES256_GCM,data:oTliCyGtPCScKbo=,iv:e7n3s02V8GNVB0wt17iDttkT/MCp1ZjN1KubTaToMrM=,tag:kLXIQ7mc7Ey5NY/r7Pz7bg==,type:str]
    AUTHENTIK_DB_USER: ENC[AES256_GCM,data:CLTJ/6IBbAnIbW6g,iv:/UgrnsoGQFeNTAXGXKqYEcOkpVw3mB52jEQiwVjxVvo=,tag:RN5XDbL/qF8zVCj23H44aQ==,type:str]
    NEXTCLOUD_DB_NAME: ENC[AES256_GCM,data:7P2ZfsYmpLal2xY=,iv:IOyEFQNt/EGbXftJJXXC2myCYhHCfg3ak4IZvWlp9Qo=,tag:XFi1cSBwiLNznZpgFI7qlQ==,type:str]
    NEXTCLOUD_DB_USER: ENC[AES256_GCM,data:P65nmePAOYS6Qs6B,iv:vP/pKs9EqoEzPVNNHqyeSWV8eeOsATWPTCqx5GgEqt0=,tag:cf41m3LXOaISYEEqlimKWg==,type:str]
    PAPERLESS_DB_NAME: ENC[AES256_GCM,data:St520+5k12KnAZ0=,iv:h9L4h+dcb1AcWPJcYFbjSsBlx2C9ar+4fVw2WdhBAsk=,tag:fMpADS8tjtRf/XZcIDIrfg==,type:str]
    PAPERLESS_DB_USER: ENC[AES256_GCM,data:9O20yo8/gRYSNk+J,iv:2K2qWSmdLPdFSUVresHEe4w9RiKJq0mqy0+I0Mn6Nic=,tag:LCXxHBXoFK0S557cnkOsiw==,type:str]
    PAPERLESS_OPENID_CLIENT_ID: ENC[AES256_GCM,data:VQUoM8NY8Mt3c8rm4vRoyVg2tTbaARKAyHLLHNCIsF6ROF5VVeDfkg==,iv:XZ/LsNE0HZA9CEf5GNN6h1xSDgqFEBuQiTpAwI0BseQ=,tag:4VGq9um4K6wgVFsNWJc8/A==,type:str]
    PAPERLESS_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:YLt3ZD5xs01QFo0TWvW8LU3LLH3hS4Cbz0mMSMt68lqqcl2tzAsJGQgXHsWl1giRX49dQAlPLBeAlof2OJe7FGI8UGwI3A8HS/dpZf1lXn+kbblKLybxNWDUfXW0GMwZDJY4wkb06/Z/u1PluaA9yyemwYIbBNHFM+2DwzOARuo=,iv:YdobVxnH7gZKXRG738OF+p4YZHsGcAHqG7JWZgtRgqI=,tag:ZxETEB65EZhLivTJK20PYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdVNXQ1lTSHo3dHVjdnRW
            SHUvbllSdzI1WnJ6S3N6bWxOZUliUnNvVUh3Clk1UnlFWUlhc1pEeE5rNkVlMFVW
            K3FpNkJYbkptcE14Y3Fxa2M3djFOUlEKLS0tIFNBMUQzaEhoUGNCM0Rsd3FYdDc1
            TkVoNU1XMUl3SGZyZEkvNUgvc1IzU1UK3Gub/dU2na602RamdbDuZawpjDpdGf+U
            9kiSw+Mlj/xgWHM7iAEiFL/cPqy62vBStCKgSsx9YTMSEUQtJ+DHZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T13:50:02Z"
    mac: ENC[AES256_GCM,data:acP2YDaZqgfzX/2SBUcIs08DIOXCzV1xCoruAqOcmY+plaMblW6FTIuYelQn/xPuhusQgvwuJDnlBnYgE9dQbXvJz30jsJt9qYssBocaBsIj4nCwvww8VS1G8629hJ57t04pgnZWalELzj8JXr8jq80EBVolCg2PJIpuVuG7GfM=,iv:kQuzrTjb5VvVz7wEAVI81AvarY6Z4kA/yKCPSODgwg4=,tag:Il1Cg2eVepe2thBEfDOdAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
