apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:u6uib+STGecLrQ==,iv:RvqRiAprSOII3/Z2MNmsh094ozNewwR3z8wT4xsuoc0=,tag:vtMVFgYmeDnrePKg4wMIMA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/yx0b37Yo4Qk3mErLL6W,iv:nWY6YYk8koEJCJ9svpM2uYcf1Auoi9/5IACgnJj3ask=,tag:jDX2zQf6jjU2r6NaK9zmxw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:FuUMY0oU7CdPAa0UmQkL/Pg/TB2vriTgDLJ9gI3iots6RA4w,iv:7R6FPDTAJ2/qcwafE2KL1zMlI+w9Cn37XLapylwtkAY=,tag:AwvqvBDXvGrUvMn2aeUNpg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:vJWRDHM13apFStU6,iv:Yc906rUw1IaWXVoVfUKZ23HDBgM6z3yf5DSFg2oCNno=,tag:CiZvndDD2rp2F+yCJ8VvzQ==,type:str]
    AWS_ENDPOINT_URL: ENC[AES256_GCM,data:1URlZ5qvqlAvO1Br3SQeSAV3RGFHWjg7BMlB5qej7on75OU0aQ==,iv:oAKzMI3JmD/GKzLjs7rcsd/0tuEE/QWXj250phiWT8E=,tag:ls5sU7l3+1kd3oGiFn0Ucw==,type:str]
    AUTHENTIK_DB_NAME: ENC[AES256_GCM,data:ssfwROi04G3id7w=,iv:06VZNwVXzyB5ocpo1mVyTyss/MQku9DDFpTZrOA3zrQ=,tag:ifdv8ud181LIY8RyKjUueg==,type:str]
    AUTHENTIK_DB_USER: ENC[AES256_GCM,data:h5MIhMAxWsCAVe1O,iv:SInCyT8lSQQl8LX/uPHro5AHFsk2kd3+bHlK9WfIqvM=,tag:OfURwlFieJE+p8P6r2NCFw==,type:str]
    NEXTCLOUD_DB_NAME: ENC[AES256_GCM,data:gibXZ1DXDwKI3u8=,iv:bXYj8b4iYjZkRLdsITLf+qnkK1KH6nP8980mAtwh9BU=,tag:x87AHtiLWVu44jjRGL7KJg==,type:str]
    NEXTCLOUD_DB_USER: ENC[AES256_GCM,data:k5Fm4uUtrXSzGGaY,iv:SbYrTvkD6gQZBAq4yohrphGTPRBfwjyA24n0hux3G8M=,tag:CAUAeUF8i72GA8sNzRykZQ==,type:str]
    PAPERLESS_DB_NAME: ENC[AES256_GCM,data:7E5vV80uYam7OIw=,iv:4vLCW4GF7bo6Foj/auJLHQ7Z6VREKBBEI9U95MixoEM=,tag:Zgxxb2J58iNMMH43p1h4Lw==,type:str]
    PAPERLESS_DB_USER: ENC[AES256_GCM,data:zo4riRZcKbCvbG8S,iv:i6bdXsS3jyF7iExBQ+mclJiAI6VnjEwdwZS18NTTHsU=,tag:NTdpZTnc1kPbXcofzkJVQg==,type:str]
    PAPERLESS_OPENID_CLIENT_ID: ENC[AES256_GCM,data:/kDntF8N43pt8YoO5kBg5RNayXSPxzaZhR8x1TN4B6J/RAbk7J2sCQ==,iv:FCwxIfA9CfNoGcPiCQEJwIw1O57r8cyuDBzzEqKr0iA=,tag:lzcpt5eyzgiQlWqANoALuQ==,type:str]
    PAPERLESS_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:SS3Q4sPH7PoN95iPMyAtnotzzNc7SBOW0XuuDu8C7XAE3AnhvfODkN2NCixRjZ3W0k3H5hXwSi1AVKqbKr1GXa6btoKNBu0H/zHYzzPeMegrn1PcNXzwNAY8BnoYVr4s9j6mBH3PZf+Wb2xo/DL8yhMsFHkGsJFW2zY9S8ixw5o=,iv:MGKJg3rg31TUmAph2+OyH7SlbnpMsmIxMZQMY8mCyqM=,tag:t7jYSUiDr5pON8w1AfehCg==,type:str]
    MASTODON_DB_NAME: ENC[AES256_GCM,data:/A3fJJ72k6LX+A==,iv:phALxyYkaGfoYCdkLPMTfw74ahmdRzTGDWCt7Kw/lG4=,tag:5gaCsKjzV+gPBLZvE1IR8w==,type:str]
    MASTODON_DB_USER: ENC[AES256_GCM,data:C02TCP9pAN/80po=,iv:PNytisBXvBIcM8JfIxcJ6MDnN6lTwRr5ZYy0AbzqGgU=,tag:OCoJdHoVj0eMdbH+1jDz8Q==,type:str]
    MASTODON_ADMIN_USER: ENC[AES256_GCM,data:2dFI3H56GNqJ/w==,iv:Z4PuI8bJKvGiQB/qSpMZxeIy/SHKZBemvE/QHLXNXQk=,tag:vVdLiXGCBZY7y8ss7NMZkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWGg1T0Rnb3lVSUtpNFlm
            THJYMk1VNTFQeDRqQVhqWDA0bGNsVkVkOTBVClNaQkxCY3pyT2xyeVJWVkdiYThl
            Z3BtRnE1eVZnNHNxVnVnNXo2SDRUeDgKLS0tIFJCc0VYUGhYWkorRnJDaG1kdlN5
            Q3dWRW1laTVxK1AzSWx1MktUdU5BcFUKfEOu+mvzUJSWTNVY9FxboubK6iBIkTdE
            3JCkBQLOBYBt9QvVCWB0/OTAPNfw3nSCzDmsKFuZufNcD9qR+Uz0tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-02T14:26:27Z"
    mac: ENC[AES256_GCM,data:wb835EjLJt9ix60/qd1OeQemTfpNVPbS+qLLyXsz+IAuYcmLv49D0AXoRzLkqBGYoseN/lppjANh0DLZSXiN8CbmYvf5AQupNTxk8cFwUicMp4OVOibCvNWXQ72BQETfZteLefkAKf4HZkHT+h2MJ7+89mLEZGADQwJHHg34HWc=,iv:acYDbERhdW5slS7p/qsulb37kTIxwO3TG/voms53i6U=,tag:QfG7hA24Ns7WEFo3WCXNhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
