---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openwebui-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .OPENWEBUI_DBUSER }}"
        password: "{{ .OPENWEBUI_DBPASS }}"
        ACCESS_KEY_ID: "{{ .MINIO_K8SPOSTGRES_KEYID }}"
        SECRET_ACCESS_KEY: "{{ .MINIO_K8SPOSTGRES_SECRET }}"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: openwebui
