---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postiz
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postiz-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .POSTIZ_JWT_SECRET }}"
        DATABASE_URL: "postgresql://{{ .POSTIZ_DB_USERNAME }}:{{ .POSTIZ_DB_PASSWORD }}@cnpg-postiz-rw.productivity.svc.cluster.local:5432/postizdb"
  dataFrom:
    - extract:
        key: postiz
