---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mixpost
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mixpost-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_DATABASE: "{{ .MIXPOST_DB_NAME }}"
        DB_USERNAME: "{{ .MIXPOST_DB_USERNAME }}"
        DB_PASSWORD: "{{ .MIXPOST_DB_PASSWORD }}"
        APP_KEY: "{{ .MIXPOST_APP_KEY }}"
        MYSQL_ROOT_PASSWORD: "{{ .MIXPOST_MYSQL_ROOT_PASSWORD }}"
        MYSQL_DATABASE: "{{ .MIXPOST_DB_NAME }}"
        MYSQL_USER: "{{ .MIXPOST_DB_USERNAME }}"
        MYSQL_PASSWORD: "{{ .MIXPOST_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: mixpost
