---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mixpost
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"
        secret.reloader.stakater.com/reload: "mixpost-secret"
    controllers:
      main:
        containers:
          mixpost:
            image:
              repository: inovector/mixpost
              tag: v1.7.2
            env:
              APP_NAME: Mixpost
              APP_DEBUG: false
              APP_DOMAIN: ${SECRET_DOMAIN}
              APP_URL: https://${SECRET_DOMAIN}
              DB_HOST: mixpost-mysql.productivity.svc.cluster.local
              DB_PORT: 3306
              REDIS_HOST: dragonfly.database.svc.cluster.local
              REDIS_PORT: 6379
            envFrom:
              - secretRef:
                  name: mixpost-secret
          mysql:
            image:
              repository: mysql
              tag: 9.1.0
            envFrom:
              - secretRef:
                  name: mixpost-secret
    service:
      mixpost:
        controller: main
        ports:
          http:
            port: 80
      mysql:
        controller: main
        ports:
          http:
            port: 3306
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "mixpost.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: mixpost
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: mixpost-pvc
        advancedMounts:
          main:
            mixpost:
              - path: /var/www/html/storage
                subPath: app
            mysql:
              - path: /var/lib/mysql
                subPath: database
