---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: budibase
spec:
  interval: 1m
  chart:
    spec:
      chart: budibase
      version: 3.0.340
      sourceRef:
        kind: HelmRepository
        name: budibase
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    serviceAccount:
      create: true
    service:
      type: ClusterIP
      port: 10000
    ingress:
      enabled: true
      className: "internal"
      hosts:
        - host: &host budibase.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: proxy-service
                  port:
                    number: 10000
    globals:
      budibaseEnv: PRODUCTION
      tenantFeatureFlags: ""
      enableAnalytics: "0"
      selfHosted: "1"
      multiTenancy: "0"
      offlineMode: "0"
      httpMigrations: "0"
      automationMaxIterations: "200"
      createSecrets: true
      tempBucketName: "k8s-budibase"
      smtp:
        enabled: true
        host: "${SECRET_MAIL_SERVER}"
        port: "25"
        from: "Budibase <mail@${SECRET_DOMAIN}>"s
    services:
      dns: cluster.local
      proxy:
        replicaCount: 1
        upstreams:
          minio: "https://s3.{SECRET_DOMAN}"
        startupProbe:
          failureThreshold: 30
          periodSeconds: 3
        readinessProbe:
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
        autoscaling:
          enabled: false
      apps:
        replicaCount: 1
        logLevel: info
        httpLogging: 1
        extraEnvFromSecret:
          - name: REDIS_PASSWORD
            secretName : budibase
            secretKey: REDIS_PASSWORD
          - name: MINIO_ACCESS_KEY
            secretName : budibase
            secretKey: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_KEY
            secretName : budibase
            secretKey: MINIO_SECRET_KEY
        startupProbe:
          failureThreshold: 30
          periodSeconds: 3
        readinessProbe:
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
          targetCPUUtilizationPercentage: 80
      automationWorkers:
        enabled: true.
        replicaCount: 1
        logLevel: info
        extraEnvFromSecret: []
        #  - name: MY_SECRET_KEY
        #    secretName : my-secret
        #    secretKey: my-secret-key
        startupProbe:
          failureThreshold: 30
          periodSeconds: 3
        readinessProbe:
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 30
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
          targetCPUUtilizationPercentage: 80
      worker:
        replicaCount: 1
        logLevel: info
        httpLogging: 1
        extraEnvFromSecret:
          - name: REDIS_PASSWORD
            secretName : budibase
            secretKey: REDIS_PASSWORD
          - name: MINIO_ACCESS_KEY
            secretName : budibase
            secretKey: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_KEY
            secretName : budibase
            secretKey: MINIO_SECRET_KEY
        startupProbe:
          failureThreshold: 30
          periodSeconds: 3
        readinessProbe:
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
          targetCPUUtilizationPercentage: 80
      couchdb:
        enabled: true
        backup:
          enabled: false
      redis:
        enabled: false
        port: 6379
        url: "dragonfly.database.svc.cluster.local"
      objectStore:
        minio: false
        region: "eu-central-1"
        url: "https://s3.${SECRET_DOMAIN}"
    couchdb:
      clusterSize: 1
      image:
        repository: budibase/couchdb
        tag: v3.3.3-sqs-v2.1.1
        pullPolicy: Always
      extraPorts:
        - name: sqs
          containerPort: 4984
      service:
        extraPorts:
          - name: sqs
            port: 4984
            targetPort: 4984
            protocol: TCP
      enableSearch: false
