---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-paperless
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: cnpg-paperless
