apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: "Disallow :latest tag"
    policies.kyverno.io/category: "Best Practices"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/subject: "Container Images"
    policies.kyverno.io/description: "Disallow use of the :latest image tag in all container types (BSI SYS.1.6.A17)."
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: require-non-latest-tag
      match:
        resources:
          kinds: ["Pod"]
      validate:
        message: "Use of the 'latest' image tag is not allowed (BSI SYS.1.6.A17)."
        foreach:
          - list: "request.object.spec.containers[]"
            deny:
              conditions:
                any:
                  - key: "{{ regex_match('.*:latest$', element.image) }}"
                    operator: Equals
                    value: "true"
          - list: "request.object.spec.initContainers[]"
            deny:
              conditions:
                any:
                  - key: "{{ regex_match('.*:latest$', element.image) }}"
                    operator: Equals
                    value: "true"
          - list: "request.object.spec.ephemeralContainers[]"
            deny:
              conditions:
                any:
                  - key: "{{ regex_match('.*:latest$', element.image) }}"
                    operator: Equals
                    value: "true"
