apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-clusterrole-wildcards
spec:
  validationFailureAction: enforce
  rules:
    - name: restrict-clusterrole-wildcards
      match: { resources: { kinds: ["ClusterRole"] } }
      validate:
        message: "ClusterRoles must not use wildcards."
        deny:
          conditions:
            any:
              - key: "{{request.object.rules[].resources[]}}"
                operator: Equals
                value: "*"
