---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./democratic-csi/ks.yaml
 # - ./garage/ks.yaml
  - ./minio/ks.yaml
  - ./openebs/ks.yaml
  - ./snapshot-controller/ks.yaml
