apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:0EKkoQ43lz2ej6goKWaTsP2okt+9oaS03s9NlPO8Ku4=,iv:wHvG6MwPBNxTa3bQsRuufWhRr5xM3CCTSopOT+K1HXk=,tag:Q6oIx2JqLZcATiyWaKBBsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL1U3YlJreldTY1oyZFJB
            R0h4Z1RXOWhyWThhbDVWandFTmZxQU1ld0JFCnJWZHVGZE41eDhXaWdMaC9raTJq
            WWdjeFF2TjRIRmJ2a0E1UW5XeDFZckkKLS0tIFJsdlhnVStTMDR1b3lhZmZPQkZH
            SGI0SHd2T2NseGl1ZnNoTDYySnpkWlUKxYCEgFJR1sJq/enmld3f01QlRXTSUMwu
            kExdKMq5GzNlQZZk+B704s2yYYk4/jhTwkpMltXSpzNVSDuQtPN36w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T15:05:07Z"
    mac: ENC[AES256_GCM,data:D82e7jUaCaHA7IdYale7NZagen1MH0rhppusXBBld/cHPlHSF0s0bRMBI8hEmEMp1P1Z5RUuDOFqZxXutxSVRghviNLXfuLLfaH8BJDha53f1APumOHCiaqRY5YOZdYXXtKCEXgqjAPUWxEdupyDyev9+pGPsuRW+4LOFwgZnHM=,iv:DjNgBbFwwq+HbdqrDwxldjGBjELCOrYC9XtUrS7TcWY=,tag:BI29jmucxusSl7D9YUJDIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
