apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:2ieFbn/evXH80M3iGQu2r0QuFyApltK5n+mvMtKFjrc=,iv:ZWrEAF9rkG+gRXdmegyQ9cxGAtfRfKvMHTHJgLMJU0E=,tag:JCWIGSFt8SDUAkTRIeybag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNFRKVUN4ZVpZVlJnSTFE
            T0l6RzJ4RzFIMzFQZGdIZHFUanU5UmNlYzFnCmhJTWFWWDdhN0FZd044eXJYSkVq
            QjdRVlJrQzBYMnZWQU45S0RXWFpyYWsKLS0tIDEycWsvRTc4VU9SV0l4S0NnU0Nt
            aHRLVGkvcGdHdXVFVjJibElGamVSY3MKkTJoQJqateKHgkjF7mqDs8ZK59E2uNN9
            srSlp6aZHzofk0RtMODUTubMRLPjag2huHb25SJyNaOEBY42Hwa3nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T13:15:52Z"
    mac: ENC[AES256_GCM,data:8oAnDykXk9PYEgzuofOna0A6Sbc9ecr4XZQUZFdeCMquW8z2EKN1oRoQTAmLad27GrQ4ck1H+jDj7BZdPlp31vvxiI5awD4svDuugUQlOTyCKivCzH9lwz/Z36DxdUFejyJuGyHxJUPJPVczIk5hlNL8VWEJdwHhz2BPET4z2so=,iv:cxzCbPqHNP7e/kmMZSflsB/+8uIeU40KWb0uWjn9Myo=,tag:CIeV8HwOwGP/plFgIoGBDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
