apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WjvdyAbUvT0PRUnY5hOCZIpb+SX1UMd1X9tQhWG7tbo=,iv:xJggViBbutDEOG+PIJZa+bod73/0rfy8Jw8UT/LVbOU=,tag:bUOH09VQoHVaPrTF7HQPXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdlI1RzI3WDFvZlc4Y0Uz
            SHhjbTFrSDZLSWsvUW1QaDZQTEhEUGs2NXhZClpUY0pyOUM4NFpCakx2N2VFN0t2
            T0lHWmtCWUxCcjZJMDM3bWpUd3BKUkEKLS0tIEZ5bXNHeFZSTHE4YWVFK3FzVVdh
            TnNrL1FJQnJ0SFhPSkV4Y2V6TVdMeXMKo7sbxZfjquRIGoJ2DO6+79ZChkyaYZ/k
            RV0w3HrL1GHVUXd3DMAJ/ey0XkiU6o1ylAuDQv5B6R/RWyixR3Gxvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T18:15:35Z"
    mac: ENC[AES256_GCM,data:6A0A6GNkjtfHpY2FFWw8kUjjv+HZeTSo3W/0p5dn/nmquiRef9t9/nXvSm3lPfgYd/oLE7z1HpAgaHkQkCwT63P1tcAs76MN3/q/qw7ndlXgAPLw+1uPOuzYVinwk/ks7Rs6rIEngz/nnkyTUie5nBvYLlMJj3L6dgquAau6AZI=,iv:MbHoiUSqBVqQ5wmoDT2efWw5ZKzT1wYFA8T5HoHmbfM=,tag:PUpJYINgfWiL9Xcub+WQdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
