apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WwI+Q3zTofmfyDj7gLr9giTtdMDu0WLv14FvoRZ/iwI=,iv:cuAMiEv4kONEGZHK3WEQxpsSw138NjecCL02leuCA1Y=,tag:B0PzvkC1i6Qf91pDR6LfLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcXJWWlh4V0x0bitaMTdh
            SVJ1ZDZNUWJvQk9nRDRVVnc3UUZEVnJJRjJVCnBMM2V0N2dkRGJzbjk5dGp2Szhm
            T1VKMlNveEc5bG5kb1FSa2xBU2RJbkEKLS0tIGMzMVJOYy94UlhIaWhrWUpONDVr
            OUZDamtxNmRVVWNCZHZUQVpKYkp4ZFkKOZbV94jzEgAZF+TTNhihiOu1ERfremma
            J9aMa6fGe7Gh0rPtoNeaecaHj/2XlYkdv4/4lKFAEZsZnfirrDMc0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T21:31:51Z"
    mac: ENC[AES256_GCM,data:js6YEaGT/wa6nlimenAAM0qIHo2Mt/bb6B3VuyNWB/fyybQcHdEKESpD8SKv3RtaRxXFTvK0ODihQJEXtWPAiSimK8UKJ1Ic/3aTF5Ls4bSOju24FXMJecIwWb92+qij53qyKKvBd4BrUJp54FHjzJwU4Kvjl9QxL8FNdU7iGXk=,iv:yYNVDBBW6nDdnGGm5TMWCbd4CPLa2Q5TtDcIEWrmKkI=,tag:zSegG2pD1IsyYU/UeqXcpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
