---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coturn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: coturn-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        COTURN_SECRET: "{{ .NEXTCLOUD_COTURN_SECRET }}"
  dataFrom:
    - extract:
        key: nextcloud
