---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      calibre-web:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: linuxserver/calibre-web
              tag: 0.6.21-ls269@sha256:fab0fda498a1354fad88ece34119f35118faf292678e0b2c18956dfa690cd2ab
            env:
              PUID: "911"
              PGID: "1000"
              TZ: Europe/Berlin
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      app:
        controller: calibre-web
        ports:
          http:
            port: 8083
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host ebooks.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: calibre-web-config-pvc
        advancedMounts:
          calibre-web:
            app:
              - path: /config
      media:
        existingClaim: calibre-web-data-pvc
        advancedMounts:
          calibre-web:
            app:
              - path: /books
      library:
        type: configMap
        name: calibre-web-library
        globalMounts:
          - path: /books/metadata.db
            subPath: metadata.db
            readOnly: true
