---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-data-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 20Gi
