---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .AUTHENTIK_POSTGRESQL_USER }}"
        password: "{{ .AUTHENTIK_POSTGRESQL_PASSWORD }}"
        ACCESS_KEY_ID: "{{ .MINIO_K8SPOSTGRES_KEYID }}"
        SECRET_ACCESS_KEY: "{{ .MINIO_K8SPOSTGRES_SECRET }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: minio
