---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .NEXTCLOUD_POSTGRESQL_USERNAME }}"
        password: "{{ .NEXTCLOUD_POSTGRESQL_PASSWORD }}"
        ACCESS_KEY_ID: "{{ .MINIO_K8SPOSTGRES_KEYID }}"
        SECRET_ACCESS_KEY: "{{ .MINIO_K8SPOSTGRES_SECRET }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: minio
