---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mastodon-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .MASTODON_DB_USERNAME }}"
        password: "{{ .MASTODON_DB_PASSWORD }}"
        ACCESS_KEY_ID: "{{ .MINIO_K8SPOSTGRES_KEYID }}"
        SECRET_ACCESS_KEY: "{{ .MINIO_K8SPOSTGRES_SECRET }}"
  dataFrom:
    - extract:
        key: mastodon
    - extract:
        key: minio
