apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Eb9WB6vwNJo0bAv9DhBDFGOfLhUNutHX/CaKfrv5D7XWBQo48UnKsw==,iv:jLGQhWaSAL9v8RPdgoPhiapXIdRwHd3f6CtRHXg3Mb0=,tag:4vtL3YTyKLBQ8xh/bcjcPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDd2NvWkJua3lkZkMyN0M3
            d2NDR3hRYmJRYlF4ckFYZFBDbC8rMWhUSzI0CklYWHNhL0ZyS1hZems2dld3Vzkx
            c2dCdS9peTlzTXFyM0pxNUtvdnV6S3cKLS0tIEI4R0pZajUxR0NvWjZnWlRJa3Nn
            UmxNL0pUL1lBTE84UTE4M3FoVW5mSDAKH1fHL7R2Nkp+ldyUz4px+LUFUH6tjcVr
            39QdKTQfo2SfEjiurIeR4LBtO6Zp8A0GODniItL5dI31D/fFxrerlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T13:15:52Z"
    mac: ENC[AES256_GCM,data:9VZYbyd13B1CAoF28TabVBXzTl8S/fkaF1dxTIP0uDX71pn9SvVZhalTEvCjXSIFMj+0Pr+5XvLLbORlAiShBF4Lm627eQPvq+Qqbm++mt2Zr5lItgFMudX1zFGDuDhskAzEMvo5GGQINatH5+PzXtNf9A04cf6GVeEGIuvQbaU=,iv:N0V50Fa2gt/ue8bvKKSAcD/+KHuEyCX3Jx6kEHFoC00=,tag:/gjCvllU+d2SzyKuuUvRAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
