apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:8ULWx2R0CnZnYkPPAGKY6oO/qN1+ubsS3Xi7NVXrtUIV8/bYnt6V/A==,iv:lspot9SiBF5ifwMLBXGB/9/xCwHcz7VkxRjOTlkxoL8=,tag:QAyfulZ6JNfuRti0JAYDqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM1ZTbVFQSmxpbDJ2d1Ri
            aTVoOUdhOGpDSzkzN1dQZmNNQVN3MEY4SWdrCnR2bHlGWm40WUwrQVlUQndxeTNa
            WHhwS3dBZjE1K2ExZTZvTmxaV3VyTzAKLS0tIFZhd25yUG43YjBDckI4ZjYyMlJ0
            NDdweDFRZEIxQm9RU0RBQUgrTXNndmsKtn9bO/KiIO4uhUQsm10/Ao4HqBR4WNF+
            iCsmR7xLPjUH5AGH+4u9zhuSmKOMdXA8AtBud4bdWrElS7XkR4aIfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T15:05:07Z"
    mac: ENC[AES256_GCM,data:gHlnfxXmrITOd6bibXpThNlPtIC+9Ww4UFfTLjkNQ8cvmdSd8xN2LwfZQ91uOwHZ/sWzS8lmtcinpsTgF4qcqODmT2DS97CPvhIePP+iaZcz3tiSsDXgYon+Tx6vW8q4nIMSbeFpIZciBrXWcz/NABlmwUP+MBpoNocMYj44Xuo=,iv:xUJ0N4mHDDpsNXSnm41MvZ84J8DfOno11mskvTGBNIg=,tag:OKPZU1OS9Nlo2HXZebud4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
