apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:U9zCdPcbmi4fNsEbtQqsuVkWEeOAZJzXUKJhDfKKAn9Sl7PnUiv8SQ==,iv:lV97zslFLUz6whM4kOhfdTTjQ1vUsTTFXwBuAXima/A=,tag:R4gBCBILrc4KOiDa+PH3Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb0dFTnN6bkNsUVB0N1Jr
            Qi80UkExeGJYdklQWE5RU1hlZmQreHBXLzJVCmN6K3dXZU5PZzFnMlBpTEdweitr
            NWJJVkxwRGE3RGFGZm5rU2MzSTM5elkKLS0tIEpHK3lOUGR5a1pHdHdMdzMrQ3JS
            U01WenFOQ3hxRHZOWThsa0pONmZXT1kKHW8snKwjsG+ceQT6oUT1Cse1TFkaheko
            KzMO1LC4CALJDggWswC2c0ZyggJQAvaf5K6Tu4Gmc8cKscfEuBQbyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T15:11:05Z"
    mac: ENC[AES256_GCM,data:GbJ5yjP30Mw66tSqUzTEzMn0GX7P8TwAxPwPQjkSgSS7t/+diF5MNih/5MqCTOjGszDepIqAgEWBpeTzV+F7odkrUbzbYBr4Rp2Th1LEwXfTKPoKjBfxC+B4UgIJjYqxAXXhL1BRsmcD70CNk6Xv9fs2Df5qDXyVzouuoedwvFw=,iv:eZMGHcS/qmx9AXeotzSYG2ZraFHzUACm9b3cxGQUp7w=,tag:m4aZaWVoT0j7Elo/y8MhIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
