apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:KWNtNy209LZRUV9yiR2YIwOczvP/UbK5BLFK4chCLnd1mT3EI7ZUQA==,iv:XtQlr0VDW2vSxRA73PF843gxke5DzEhNswNM2jJbunk=,tag:DSE/CN38glml36QTT4V8xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j07y59p2jt2yx30zrume5rsmxplqydnnsls8mtgk82m5lt0w99tsl345rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS0pYVm5Fd0k1VnVXZVJy
            WXJNVXBMR044Q25LZGIzMUZtcnNVUDQ2RGhJCk93UkUwLzF0NUp5VjZBNlNGa3hN
            cElobFpJbXJoL21uc2VBLzhvaTB3YnMKLS0tICtLVVV0S2lEQndFV0NFeXJNcjc4
            RXpKUkhDSkVFSzA5VlV2MmIrRzY0MGsKdyWACz4HvQ1mh8NBPeo9i3IKTGRbg0a3
            9ksrKGlqSJWuYiszS6rXgHcCvQOkYmJU82ZG4gQfPMAtJi9LWphRWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T21:31:51Z"
    mac: ENC[AES256_GCM,data:8Di7mxpQj3Va0oBPlB2myDyFa0fcThUuqX9yX4D1au+L05vKZ/M7uJNXpeumlkjjMDFM/EbwE85oRT9PL7hkZ4oHsOK0vFmnqDmp9LQjDs9eojvNGLP3F7Xva6JnIg99CVoOX8XzFj4+dMJkWDYXSAfoybjO9Wsepf7lBEaS7Vs=,iv:Z5fzbbJ03QXyFZgQmHV/3MWPreljaa9d/jdi7HMjXDg=,tag:QNrLQhYZV6a4UaWZ7yJhbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
